remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Seeing the world through the lens of beer reviews
description: ADA Project of the RiskyBiscuits team
show_downloads: False
navigation:
  - title: Home
    url: /
