theme: jekyll-theme-minimal
title: Seeing the world through the lens of beer reviews
description: ADA Project of the RiskyBiscuits team
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
